#!/usr/bin/env python3
"""Verify selected source objects against a complete retail DOL link.

Use already configured/built objects. First link every extracted retail object,
then substitute only the requested source units. Both outputs must exactly equal
an original DOL verified against config/<version>/config.yml. This checks final
addresses, relocations and linker garbage collection hidden by object reports.
No matching manifest or original file is modified.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[1]
VERSIONS = ("GQPE78", "GQPP78", "GU4Y78")


def rooted(path: Path | str) -> Path:
    return (ROOT / path).resolve()


def config_scalar(text: str, key: str) -> str:
    """Read a required top-level scalar from the project's known DTK configs."""
    matches = re.findall(
        rf"^{re.escape(key)}:[ \t]*(?:\"([^\"\r\n]+)\"|'([^'\r\n]+)'|([^#\r\n]+?))"
        r"[ \t]*(?:#.*)?$", text, re.MULTILINE
    )
    if len(matches) != 1:
        raise ValueError(f"Expected one top-level {key}: in version config")
    return next(value for value in matches[0] if value).strip()


def normalize_unit(unit: str) -> str:
    return unit.strip().replace("\\", "/").removeprefix("src/")


def verify(
    version: str,
    units: set[str],
    output: Path,
    *,
    build_dir: Path = Path("build"),
    compilers: Path | None = None,
    dtk: Path | None = None,
    original: Path | None = None,
) -> str:
    if version not in VERSIONS:
        raise ValueError(f"Unknown version: {version}")
    if not units:
        raise ValueError("Select at least one source unit or a nonempty --units-file")
    build_dir = rooted(build_dir)
    build = build_dir / version
    version_config = (ROOT / "config" / version / "config.yml").read_text(encoding="utf-8")
    expected = config_scalar(version_config, "hash").lower()
    if not re.fullmatch(r"[0-9a-f]{40}", expected):
        raise ValueError("Version config hash must be a SHA-1 digest")
    original_path = rooted(original or config_scalar(version_config, "object"))
    original_data = original_path.read_bytes()
    digest = hashlib.sha1(original_data).hexdigest()
    if digest != expected:
        raise ValueError(f"Original DOL hash mismatch: {digest} != {expected}: {original_path}")

    config = json.loads((build / "config.json").read_text(encoding="utf-8"))
    known = {unit["name"] for unit in config["units"] if not unit.get("autogenerated")}
    if missing := units - known:
        raise ValueError("Source units absent from build config: " + ", ".join(sorted(missing)))
    object_lists: dict[str, list[Path]] = {"retail": [], "source": []}
    for unit in config["units"]:
        retail = rooted(unit["object"])
        source = retail
        if unit["name"] in units:
            # Derive source names from DTK's actual object paths, not the unit suffix.
            source = build / "src" / retail.relative_to(build / "obj")
        for label, path in (("retail", retail), ("source", source)):
            if not path.is_file():
                raise ValueError(f"Missing object: {path}; configure and build this version first")
            object_lists[label].append(path)

    linker = rooted(compilers or build_dir / "compilers") / "GC/2.0p1/mwldeppc.exe"
    dtk = rooted(dtk or build_dir / "tools" / ("dtk.exe" if os.name == "nt" else "dtk"))
    ldscript = rooted(config["ldscript"])
    required = [linker, dtk, ldscript]
    wrapper = build_dir / "tools/wibo"
    if os.name != "nt":
        required.append(wrapper)
    for path in required:
        if not path.is_file():
            raise ValueError(f"Missing build tool or linker script: {path}")
    output = output.resolve()
    # All writes belong to this diagnostic output directory, never orig/ or build objects.
    protected = {original_path, ldscript, *required, *object_lists["retail"], *object_lists["source"]}
    for label in object_lists:
        for suffix in ("rsp", "elf", "dol", "log"):
            if (output / f"{label}.{suffix}").resolve() in protected:
                raise ValueError("Output artifact would overwrite a link input")
    if version == "GU4Y78":
        from pad_dol import pad_dol
    output.mkdir(parents=True, exist_ok=True)
    for label, objects in object_lists.items():
        response = output / f"{label}.rsp"
        response.write_bytes(("\r\n".join('"' + path.as_posix() + '"' for path in objects) + "\r\n").encode())
        elf, dol = output / f"{label}.elf", output / f"{label}.dol"
        command = [str(linker), "-fp", "hardware", "-nodefaults", "-lcf", str(ldscript),
                   "-o", str(elf), "@" + str(response)]
        if os.name != "nt":
            command.insert(0, str(wrapper))
        log_path = output / f"{label}.log"
        try:
            with log_path.open("w", encoding="utf-8") as log:
                subprocess.run(command, cwd=ROOT, check=True, timeout=120,
                               stdout=log, stderr=subprocess.STDOUT)
                subprocess.run([str(dtk), "elf2dol", str(elf), str(dol)], cwd=ROOT,
                               check=True, timeout=120, stdout=log, stderr=subprocess.STDOUT)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
            raise ValueError(f"{label} link failed; inspect {log_path}: {error}") from error
        if version == "GU4Y78":
            # The compilation stores the DOL at 128-byte file alignment.
            # Pad only this newly linked diagnostic copy, never the original.
            pad_dol(dol, 128)
        result = dol.read_bytes()
        if result != original_data:
            raise ValueError(f"{label} link differs from retail: "
                             f"{hashlib.sha1(result).hexdigest()} != {digest}; inspect {output}")
        print(f"{version} {label}: retail SHA-1 {digest}", flush=True)
    return digest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", choices=VERSIONS)
    parser.add_argument("units", nargs="*", help="configured unit names from config/<version>/splits.txt")
    parser.add_argument("--units-file", type=Path, help="matching manifest (one unit per line; # comments allowed)")
    parser.add_argument("--build-dir", type=Path, default=Path("build"), help="build directory relative to repository root")
    parser.add_argument("--compilers", type=Path, help="compiler directory (default: <build-dir>/compilers)")
    parser.add_argument("--dtk", type=Path, help="DTK executable (default: <build-dir>/tools/dtk[.exe])")
    parser.add_argument("--original", type=Path, help="override original path; version config hash still required")
    parser.add_argument("--output", type=Path, help="directory for diagnostic ELF/DOL files and linker logs")
    args = parser.parse_args()
    try:
        units = {normalize_unit(unit) for unit in args.units}
        if args.units_file:
            units.update(normalize_unit(line.split("#", 1)[0])
                         for line in args.units_file.read_text(encoding="utf-8-sig").splitlines())
        units.discard("")
        output = args.output or Path(tempfile.mkdtemp(prefix="bfbb-source-link-"))
        verify(args.version, units, output, build_dir=args.build_dir,
               compilers=args.compilers, dtk=args.dtk, original=args.original)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    print(f"Verified {len(units)} source substitutions; artifacts: {output.resolve()}")


if __name__ == "__main__":
    main()
